const fs = require('fs');
const vm = require('vm');
const assert = require('node:assert/strict');
const path = require('path');
const html = fs.readFileSync(path.join(__dirname, 'meeting-dashboard.html'), 'utf8');
assert.equal(/<!doctype|<html|<head>|<body>/i.test(html), false);
assert.equal(/fetch\(|XMLHttpRequest|WebSocket/.test(html), false);
assert.ok(Buffer.byteLength(html) < 1000000);
assert.equal((html.match(/<details class="md-rules"/g) || []).length, 3);
assert.equal(/<details[^>]*\sopen(?:\s|>)/.test(html), false);
let script = html.match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(script);
script = script.replace('/* initial-render */render();', 'globalThis.audit={state,model,valid,lateFor,salesForOp,milestones};');
const context = {document: {getElementById: () => ({addEventListener(){}, querySelector: () => ({addEventListener(){}})})}};
vm.createContext(context); vm.runInContext(script, context);
const {state, model, valid, milestones} = context.audit;
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7, `${a} != ${b}`);
let checks=0;
for(let first=1;first<=9;first++) for(let last=first;last<=9;last++) {
  state.start=`2026-${String(first).padStart(2,'0')}`;
  state.end=`2026-${String(last).padStart(2,'0')}`;
  assert.ok(valid()); state.op='all'; const all=model();
  const sub=['人力','汽车','数字员工'].map(op=>{state.op=op;return model();});
  for(const key of ['expected','realized','delta','costTotal']) near(all[key],sub.reduce((s,x)=>s+x[key],0));
  for(const key of ['signed','net','invoice','cash','pool']) near(all.sales[key],sub.reduce((s,x)=>s+x.sales[key],0));
  near(all.sales.pool,420);
  near(all.costTotal,Object.values(all.cost).reduce((s,x)=>s+x,0));
  near(all.delta,all.expected-all.realized);
  const period=d=>!!d&&d.slice(0,7)>=state.start&&d.slice(0,7)<=state.end;
  near(all.delta,milestones.reduce((s,r)=>s+(period(r.planned)?r.amount:0)-(r.approved&&period(r.actual)?r.amount:0),0));
  assert.equal(all.pending,last===9?1:0); checks++;
}
state.start='2026-09';state.end='2026-09';state.op='all';
const sample=model();near(sample.expected,176);near(sample.realized,146);near(sample.delta,30);
near(sample.sales.signed,331);near(sample.sales.net,150);near(sample.sales.pool,420);
assert.equal(sample.ps.filter(p=>context.audit.lateFor(p).length).length,2);
state.start='2026-09';state.end='2026-01';assert.equal(valid(),false);
state.start='2026-10';state.end='2026-10';assert.equal(valid(),false);
console.log(JSON.stringify({result:'PASS',monthRanges:checks,organizations:4,checked:'汇总勾稽、商机不受时间影响、人工确认净签约、确收跨期差额、四类成本无重复、折叠区默认关闭、日期边界',sample:{expected:sample.expected,actual:sample.realized,delta:sample.delta,cost:sample.costTotal}}));
